name: "Preview Publish"

on:
  push:
    branches: [ main, develop, feat/privatization_storybook ]

env:
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  install:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules & Turbo building
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/Library/Caches/Cypress
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.run_id }}


      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build-all-components
          npx build-storybook

  build:
    needs:
      - install

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules & Turbo building
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/Library/Caches/Cypress
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.run_id }}

      - name: Run Test
        run: |
          yarn cypress info
          yarn test

      - name: Publish storybook to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SB_SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SB_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SB_SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SB_SERVER_PORT }}
          SOURCE: "storybook-static/"
          TARGET: ${{ secrets.SB_SERVER_TARGET }}/${{ github.ref_name }}