name: "Preview Publish"

on:
  push:
    branches: [ main, develop, feat/privatization_storybook ]

env:
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  install:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules & Turbo building
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/Library/Caches/Cypress
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.run_id }}

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build-all-components

      - name: Install docs dependencies
        run: |
          cd ./docs
          yarn install --frozen-lockfile
          cd ..

  build:
    needs:
      - install

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules & Turbo building
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/Library/Caches/Cypress
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.run_id }}

      - name: Run Test
        run: |
          yarn cypress info
          yarn test
          
      - name: Publish to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json

      - name: Build storybook
        run: NODE_OPTIONS=--max-old-space-size=11264 npx build-storybook

      - name: Publish storybook to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SB_SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SB_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SB_SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SB_SERVER_PORT }}
          SOURCE: "storybook-static/"
          TARGET: ${{ secrets.SB_SERVER_TARGET }}/${{ github.ref_name }}
          AGRS: "-rlgoDzvc --delete"

      - name: Import docs i18n
        run: yarn import-docs

      - name: Deploy docs to sb-static branch
        run: |
          yarn deploy-storybook -- --branch=sb-static

      - name: Deploy docs to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
